### ISSUE TITLE
Hikes process

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/hikes#1]
Initial Suggestion for hikes script generation.

1. An issue is opened with a topic for a hike.  Must include a category for inclusion
2. A PR is created with initial script in a new markdown file in the folder that matches the category
3. Once the script is finalized it will marked as so. Now the script is ready to be made into a video.
4. Once the video has been created, the topic can be marked as completed and a hikes challenge is to be created from this script/video in the main repo

This is open for discussion by those hoping to contribute.

Happy Coding!

**Comment by brianamarie** [comment]
A few questions:

- Do we want to make a master list of categories? Categories that already exist or categories we'd like to see? With many people contributing, it's important to have a solid outline as individuals may categorize smaller topics into different units which could lead to non-linear videos overall. 
- Should we assume that whomever writes the PR for the script will also be doing the filming?

**Comment by BerkeleyTrue** [comment]
1a. We could create a folder for each category in this repo. 
1b. Categories should be for hikes upcoming. 
2. No I don't think that should be an assumption.

**Comment by freeradik** [comment]
What do we do if a Hike can possibly be classified under two categories? Will tags work better under this scenario. A Hike can have multiple tags. Or possibly a combination of categories and tags where a Hike belongs to one category but can belong to multiple tags. I was thinking of something similar to the gmail folder and label idea? Tags might also possibly make it easier for searching. 

and also what is a PR?

**Comment by BerkeleyTrue** [comment]
Hikes should fall into a category. Hikes will be linear, just like challenges, so the categories will be used to determine the order they appear. 

[Pull Request](https://help.github.com/articles/creating-a-pull-request/) (PR).

**Comment by freeradik** [comment]
Sounds good. Let me know how i can help. 
Just to give a bit of background, I am new to almost everything except a bit of programming which i learned and used in a previous life as a graduate student  about 10yrs back. Mainly C, C++ and some JAVA. 
Eager to help freeCodeCamp in anyway i can with a bit of initial guidance.

**Comment by brianamarie** [comment]
I just created hikeList, a json formatted file of current hikes. I'm going to add other categories for expected topics, like UI dev or design. 

If a hike could technically be two or more categories, we need to make a hard decision about where it needs to go to make most sense to the users. Think of categories like units, and each video like an individual lesson. Even though the lesson could fit into multiple units, we need to plan for the best understanding to beginners.  One possible fix could be an introductory video that's more appropriate for beginners in an earlier unit, then more extensive videos later on when the user has more supporting knowledge. 

So, UI Design & Development, Web Design...what other categories should I add? Scripts for those categories can be submitted asap so we can read through and get started on filming and get them up on youtube and vimeo.

**Comment by freeradik** [comment]
To the extent of my knowledge the list looks pretty comprehensive. 
I am wondering if there is a need to have a category called ***Algorithms*** though, maybe have scripts/videos for explaining different algorithms like sorting, searching etc. or will that be outside the scope of hikes?

**Comment by brianamarie** [comment]
freeradik, I think a category of Algorithms is a great idea. An intro video could discuss what an algorithm is and when it's used. Each video after could focus on a different common algorithm and the type of logic that is used when writing algorithms in JS or any other language. Does this sound like something you'd be interested in scripting/recording?

**Comment by shankarkd** [comment]
@brianamarie yes i will be interested in doing the scripting/recording for some hikes in the ***Algorithm*** category. If its ok i would like to see how the first hikes in other categories are done and try to replicate a similar *theme* for hikes in Algorithm.

**Comment by brianamarie** [comment]
@shankarkd Here are my scripts for the "JS Lingo" videos. https://docs.google.com/spreadsheets/d/1ekFnD9yxbAF0Bl7m6ptQo3PfIaqj1Tl8HVV9k4QJvTM/edit?usp=sharing

You can view the videos here. 
https://www.youtube.com/watch?v=fahY2YY5Atg&list=PLWKjhJtqVAbmfoj2Th9fvxhHIeqFO7wOy&index=22

**Comment by shankarkd** [comment]
thanks for that @brianamarie. Looking at the script for the **JS Lingo**, i think it might be helpful to add hike(s) on ***JS Errors***. Let me know what you think.

**Comment by brianamarie** [comment]
I think that's a great idea. As with the other topics, I don't totally know what that would look like, but I can see that topic being very helpful.

**Comment by jameswinegar** [comment]
Another note, questions should be T/F and provide a "help message" when someone answers incorrectly

example

Do birds have wings? T 
&nbsp;&nbsp;&nbsp;&nbsp;Remember what birds use to fly around, you got this!

**Comment by QuincyLarson** [comment]
Closing this for now since we've ironed most of these issues out.
