### ISSUE TITLE
Discrete Mathematics 8: Associative & Commutative Laws - Script

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#10]
Hello world! It's Shawn again, and in this video I will be introducing the concepts of commutativity and associativity. Let us begin.

In set theory, both the the union and intersection operators are commutative. That is, changing the order of the sets doesn't change the result.
      e.g. A = {1,2,3}, B = {2,3,4},  AUB = BUA = {1,2,3,4}, C = {x,y,z}, D = {w,y,z},  C∩D = D∩C = {y,z}

Now, associativity is another operation, but this time at least three sets are present. The law states that changing the order of operations performed on the sets, will not change the order of the result.
     e.g. A = {1,2},  B = {2,3}, C = {3,4},  (AUB)UC = AU(BUC) = {1,2,3,4}, (A∩B)∩C = A∩(B∩C) = {} = Ø

******************************************************************************************************************
Again, these are rough drafts, and I will be polishing them off. I decided to introduce the the laws in terms of sets instead of the general case. I'm worried that otherwise the topic may be too abstract for most campers.

**Comment by jameswinegar** [comment]
Add distributive law
