### ISSUE TITLE
Discrete Mathematics 7: Examples (Set Operators)

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#11]
Hello World! It's Shawn Grooms again. I wanted to help everyone visualize the union and intersection of sets, so this video uses venn diagrams to illustrate those ideas.

Show venn diagrams for 2-3 minutes.
Will include, but not limited to, the following:
- Let A = {1,2,3}, B = {3,4}, C = {2,3,4}
- A∩B
- A∩C
- B∩C
- AUB
- AUC
- BUC
- A \ B
- B \ C
- R \ Q = I

**Comment by jameswinegar** [comment]
Rename "Examples of Set Operators"

**Comment by jameswinegar** [comment]
R-Q is I, write two different ways
