### ISSUE TITLE
Discrete Mathematics 9: Examples (Associativity & Commutativity) - Script

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#12]
Hello World! It's Shawn Grooms again. I wanted to help everyone visualize the union and intersection of sets, so this entire video are just examples.

Show venn diagrams for 2-3 minutes.
Will include, but not limited to, the following:

Let A = {alpha, beta, gamma}, B = {beta, gamma}, C = {gamma, delta}  **Will use letters in video***
- (A∩B)UC
- A∩(BUC)
- (AUB)∩C
- AU(B∩C)
- A∩B∩C
- AUBUC
- A∩(BUC)
- AU(B∩C)
- (A∩B)U(BUC)
- (A∩B)∩(BUC)

******************************************************************************************************************
If you have a burning desire for different sets, just let me know! I ended the video with a couple easy ones as a confidence builder. Also, I chose to use greek letters because it catches people off guard, and I want to stress the insignificance of it. I will be explaining complements in the next video.

**Comment by jameswinegar** [comment]
Add distributive examples
