### ISSUE TITLE
Discrete Mathematics 16: Statements

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#128]
Hello world! Shawn Grooms here, and congratulations on making it to the logic section of discrete mathematics. In this video I wanted to introduce the concept of statements.

In logic, a statement is defined as a declarative sentence that can be verified as true or false.
e.g. "The integer 3 is greater than 5" is a false statement since 3 < 5.

Examples of sentences that aren't statements are:
1) Open sentence: "The integer x is greater than 5" can't be verified since x is any integer value.
2) Imperative (command) sentence: "Substitute the integer 7 for x."
3) Interrogative (question) sentence: "Is A a subset of B?"
4) Subjective (opinion) sentence: "Cats are great!"

Examples of the same sentences after being corrected:
1) Let x = 13. The integer x is greater than 5.
2) Note, it is impossible to correct this sentence and make it a statement, because it is too ambiguous.
3) A is a subset of B.

Statements are often denoted with the letters P & Q in order to more easily analyze them.
e.g. We would let "The integer 3 is greater than 5" = P.

This allows us to say whether P is true or false. This is often put in what is know as a truth table.
[P]
T
F
See the next video to learn about negations and more on truth tables.
**************************************************************************************************************
Are the following statements?
- Dogs are awesome!
- Elephants weigh more than hippos.
- Giraffes are taller than mice.
- Is this a statement?
- This is a statement.
- Let x equal 17.

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
