### ISSUE TITLE
Discrete Mathematics 17: Negations

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#129]
Hello world! It's Shawn Grooms again. In the video I will introduce the concept of negations.

The negation of a stament is simply the logical complement of a statement. This concept should be familiar, but if it isn't, watch Discrete Mathematics 12 & 13 for review. 

The notation for negation are as such:
! : This is used in most by computer scientist when coding, but avoided in mathematics, as it can mean both factorial and "unique".
~ : This symbol is called a tilda and is another common way to express negation, but I again avoid it as it can mean different things to me depending on the concept.
*symbol* : This is my preferred symbol to show negation, as I have yet to see it used in any other subject

Now lets will jump right into examples.

Consider the following statemetns:
P:  x is greater than 5.
Q: A is a subset of B.
R: 7 is even.
S: All athletes are at least 6 feet tall.

~P: x is not greater than 5, which is to say x is less than or equal to 5
~Q: A is not a subset of B.
~R: 7 is not even, which is to say 7 is odd.
~S: There exists an athlete that is less than 6 feet tall.

Note: ~S introduces the idea of a counterexample. In the world of logic if you can find one situation (case) in which the statement isn't true, then it is false. Therefore, for a statement to be false, you only need one counterexample.

Corresponding Truth Table:
[P]__[~P]
T____F
F____T

*****************************************************************************************************************
Find the negation of these statements:
- All turtles weigh 10 pounds.
- No one speaks Esperanto.
- Everyone loves to eat chocolate.
- No one can lift 10,000 pounds.

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
