### ISSUE TITLE
Discrete Mathematics 6: Set Operators - Script

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#13]
Hello World! It's Shawn Grooms again. In this video I'm going to introduce some operations we can do on sets: unions, intersections, and set difference. This video will introduce the theory and followed by a video with more examples.

Let A = {1,2}, B = {2,3}

U: The "union" of two sets creates a new set. AUB = {x : x is an element of A  or x is an element of B}
      e.g. AUB = {1,2,3}

∩: The "intersection" of two sets also creates a new set. A∩B = {x : x *symbol* A and x *symbol* B}
      e.g. A∩B = {2}
\ : The "difference" of two sets also creates a new sets. A \ B = {x : x *symbol* A and x *symbol* B}
     e.g. A \ B = {1}

Examples will be in the next video.

**Comment by jameswinegar** [comment]
Rename to "Set Operators"

**Comment by jameswinegar** [comment]
Questions
----------------

Bob and Sue are married, Bob and Jim are brothers? What happens to them?

Let A = {Bob, Sue}, B= {Bob, Jim}

A union B = MC - {Bob}, {Sue} , {Bob, Sue, Jim}, {Sue, Jim} ( {Bob, Sue, Jim} )
A intersect B = MC - {Bob}, {Sue} , {Bob, Sue, Jim}, {Sue, Jim} ( {Bob} )
A \ B = MC -  {Bob}, {Sue} , {Bob, Sue, Jim}, {Sue, Jim} ( {Sue} )
