### ISSUE TITLE
Discrete Mathematics 18: Conjunctions & Disjunctions

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#130]
Hello, world! It's Shawn Grooms again and the topics of this video are conjunctions and disjunctions. Instead of saying conjunction and disjunction, it is commonplace to say "and" and "or". The similar operations in set theory are: intersection and union.

Notation for a conjunction is:
- Different programming languages: and, &, &&
- In mathematics: *concave chevron*

Notation for a disjunction is:
- Different programming languages use: or, |, ||
- In mathematics: *convex chevron*

e.g. Let P = "All wardrobes lead to Narnia", Q = "All apples are not round"
The resulting conjunction is:
- P *concave chevron* Q, which is read as "P and Q"
- P *concave chevron* Q = "All wardrobes lead to and Narnia and all apples are not round."
- ~P *concave chevron* Q = "There exists a wardrobe that doesn't lead to Narnia and some apples are not round."

The resulting disjunction is:
- P *convex chevron* Q, which is read as "P or Q"
- P *convex chevron* Q = "All wardrobes lead to Narnia or all apples are not round."
- P *convex chevron* ~Q = "All wardrobes lead to Narnia or there exists a round apple."

You may be wondering why the truth table below has 4 rows instead of 2. This is a topic for a later video, so for the time being please bear with me by accepting it as fact.
The resulting truth tables for conjunctions and disjunctions are as follows:
[P]---[Q]----[P&&Q]---[P||Q]
T------T---------T---------T
T------F---------F---------T
F------T---------F---------T
F------F---------F---------F

Another way to think about truth tables is in terms of binary. Let F = 0 and T = 1. For a conjunction, if the number of statements (columns) equals the sum of their row, the conjunction is true and otherwise false. Now for a disjunction, if the sum of the statements is greater than 0, the statement is true and otherwise false.

e.g. When analyzing the first row, start by calculating the sum of the first row. Since there are 2 statements (i.e. P,Q) and this equals sum of the row [P&&Q] == T. Also, since the sum of the row is greater than 1, [P||Q] == T. Continue this process for the three remaining rows.

[P]---[Q]     [P&&Q]---[P||Q]
1------1            T---------T
1------0            F---------T
0------1            F---------T
0------0            F---------F

********************************************************************************************************
What are the resulting conjunctions and disjunctions:
- P&&Q
- P||Q
- P && ~Q
- ~P && Q
- ~P && ~Q
- P || ~Q
- ~P || Q
- ~P || ~Q
- ~(P&&Q)
- ~(P||Q)

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
