### ISSUE TITLE
Discrete Mathematics 19: DeMorgan's Law & Logical Equivalence

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#131]
Hello, world! It's Shawn Grooms here with FreeCodeCamp. This video will introduce DeMorgan's Laws in terms of logic, and the concept of logical equivalence.

In set theory, we defined DeMorgan's Laws as:
1) The complement of a union, is the intersection of the complements.
2) The complement of an intersection, is the union of the complements.

Now in logic, we define DeMorgan's Laws as:
1) The negation of a conjunction, is the disjunction of the negations.
2) The negation of a disjunction, is the conjunction of the negations.

*Note: This shouldn't be a new concept for you! But, if it isn't sounding familiar I, suggest watching Discrete Mathematics 14 & 15.

Fortunately, this transitions us into a conversation about logical equivalence. In set theory we could simply us equivalence when comparing sets. i.e. (A intersect B)^c = A^c union B^c
But, it doesn't make sense to say that the truth value of two different statements are equal.
e.g. P = "2 < 5", Q = "7 > 4" Although both P and Q are true statements, we wouldn't call them equal.
2 <5 = 7 > 4 simply doesn't make sense. However, we would say that they have a logically equivalent, as they have identical truth values.

Logical equivalence notation:
- In programming languages: ==, ===
- In mathematics: *triple equals symbol*
e.g. P === Q would be spoken as, "P is the logical equivalent to Q"

The corresponding truth table would look as such:
[P]---[Q]---[~P]---[~Q]---[P&&Q]---[~(P&&Q)]---[~P||~Q]---[P||Q]---[~(P||Q)]---[~P&&~Q]
T------T-------F-------F--------T--------------F--------------F----------T------------F------------F
T------F-------F-------T--------F--------------T--------------T----------T------------F------------F
F------T-------T-------F--------F--------------T--------------T----------T------------F------------F
F------F-------T-------T--------F--------------T--------------T----------F------------T------------T

A big secret to truth tables is not stress out. They can start to look pretty ugly, but when you break them down column by column, they aren't hard...just time consuming. However, understanding these truth tables can make your code much simpler and faster.
************************************************************************************************************

Are the following statements logically equivalent?
- ~(P&&Q) === ~P || ~Q
- ~(P||Q) === ~P && ~Q
- ~(P||Q) && ~(P&&Q) === ~Q && ~P === ?
- P && ~P === ?
- Q || ~Q === ?
- P && ~P && ~P && P && ~P === ?

**Comment by SEGrooms** [comment]
See basic javascript: waypoint 66

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
