### ISSUE TITLE
Discrete Mathematics 20: Implications

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#133]
Hello, world! Shawn Grooms here with FreeCodeCamp. In this video I will introduce on of my favorite concepts, implications. Implications are the basis of most of mathematics. Seriously, you wouldn't believe the affect this *simple* concept has had on the world! So, don't move on until you have a good handle on this concept. Alright? Now take a deep breath, and we'll begin.

An implication is a statement formed by the truth values of two other statements. The notation for this is P ==> Q, and is read as "If P, then Q" or "P implies Q". Also, keep in mind that in logic we only care about the truth value of an implication, not the meaning.
i.e. We could easily have examples where P =  "All fluffy kittens eat rocks." and Q = "Giant marshmallows with legs sprint faster than Usain Bolt."
Yes, these are more entertaining, but we only car about their truth values.
i.e.
- Do all fluffy kittens eats rocks? Which is to say, can we find a counterexample a fluffy kitten that doesn't eat rocks?
- Do all giant marshmallows with legs sprint faster than Usain Bolt? Which is to say, can we find a counterexample where a giant marshmallow with legs sprints slower or equally fast as Usain Bolt?

e.g.
P: You work really hard.
Q: You learned how to program.
P ==> Q: If you work really hard, you will learn how to program.
Here is the corrseponding truth table that I will explain below.
[P]---[Q]---[P==>Q]
T------T---------T
T------F---------F
F------T---------T
F------F---------T

Now, you may be confused about the truth values of the implication, and that's why I love them! They confused me when I was first introduced to them, but this is your first real glimpse into the world of mathematical logic. I want to explcitly state that implications are not the same thing as conjunctions and disjunctions! This is something a lot of people try to draw parallels to, but you can't. This is a new topic. So we are now simply working with our deductive skills at this point.

This topic can best be explained as a teacher making promise.

Consider that your teacher promises the following to you.
If you work really hard, you will learn how to program.

Truth table:
1st Row: Both P and Q are true. So, did your teacher tell you the truth? Well, yes. You worked really hard, and you learned how to program, so the resulting implication is true!

2nd Row: Now, P is true and Q is false. So, did your teacher tell you the truth? It doesn't look like it. Because, your worked really hard, but you didn't learn how to program. So, the implication is false.

3rd & 4th Rows: P is false and Q is true. So, did your teacher tell you the truth? Yes, remember that P is the promise that "If you work hard...", but in this case you didn't work hard. Therefore, your teacher was telling the truth. The teacher was being honest, and is innocent of the results of Q. So, the implication is true. We would say that the 3rd and 4th rows are "vacuously true".

****************************************************************************************************************
What are the resulting truth tables for:
- P ==> Q
- P ==> ~Q
- ~P ==> Q
- ~P ==> ~Q
- Q ==> P
- Q ==> ~P
- ~Q ==> P
- ~Q ==> ~P
- (P ==> Q) ^ (Q ==> P)

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
