### ISSUE TITLE
Discrete Mathematics 21: Cases & MN-Rule

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#134]
Hello, world! Shawn Grooms here for FreeCodeCamp. This video will introduce the concept of cases and introduce the MN-Rule.

I would like to start by explaining why a truth table with 1 intitial statment results in 2 rows and 2 intial statements result in 4 rows.

Consider the statement P. We know that P has 2 possible solutions, or "cases".  ***begin drawing decision tree*** Now if we look at our second statement Q, we know that Q also has 2 cases.
***Add more branches to tree*** Now, if you follow all possible paths to a final node, you will find four paths. Thus, we have four decisions, or "cases". You may have hypothesized that simply multiplying the number of cases of P by the number of cases of Q will give you the number of possible cases. i.e. 2 * 2=4  If you did, then you are correct. This is a result of the "Fundamental Counting Principle", but it is commonly referred to as the M*N-Rule.

M*N-Rule: Consider a situation where there are m-ways of completing one task, and n-ways of completing another task, then there are m*n ways of completing both tasks.

e.g.
If we added a 3rd initial statement, R, how many total cases would their be? First recall all statements are binary (i.e. true or false), which is to say all statements will only have 2 cases. Then when applying the M*N-Rule you should find that there are 8 possible cases. i.e. 2 * 2 * 2 = 8.

In fact, all possible cases = 2^k , where k is the number of initial statements.

Keep this concept in mind while we move forward, as it is a very important one! Also, I hope you noticed that this is the reasoning behind find the number of elements in the powerset of a given set. I introduced this idea in Discrete Mathematics 11, but never explained why. You now have the tools to understand the reason why the P(A) = 2^|A|, where A is a finite set.

*********************************************************************************************************
Calculate the number of cases, and figure out the significance of these numbers.
- for 9 statements?
- for 10 statements?
- for 20 statements? *Hint*: 2^20 = 1024^2
- for 30 statements? *Hint*: 2^30 = 1024^3

https://www.youtube.com/watch?v=_uWzpyr_5qk&index=5&list=PLWKjhJtqVAbmfoj2Th9fvxhHIeqFO7wOy

**Comment by SEGrooms** [comment]
@brianamarie I linked your video to this subject. If you stumble upon any other topics in which that would be appropriate, let me know.

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
