### ISSUE TITLE
Discrete Mathematics 22: Truth Tables 1 (Trivial & Contradiction)

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#135]
Hello, world! Shawn Grooms here for FreeCodeCamp. The next 4 videos will all be elaborating on truth tables. I will use these truth tables to introduce terms and/or definitions.

We will begin by constructing a basic truth table an implication.
[P]---[Q]---[P==>Q]
T------T---------T
T------F---------F
F------T---------T
F------F---------T

As stated in Discrete Mathematics 20, if we find P to be false, then the implication P==>Q is called "vacuously true". If this doesn't sound familiar, please rewatch that video.

Now another immediate truth we can find, is when an implication is "trivially true". For this type of truth, we assume P is true. We ignore the idea of P being false, since we have established that any implication of this form is vacuously true. So, when we assume P is true, we are only concerned with two cases. Now, if we find Q to be false it doesn't have a name, because we don't care about it. However, if we find Q to be true, then P==>Q is true, and said to be "trivially true".

One of the previous challenge problems were to show the truth value of [P && ~P] and [P||~P]. Did you figure them out?
[P]---[~P]---[P&&~P]---[P||~P]
T-------F--------F------------T
F-------T--------F------------T

The conjunction in this table is called a "contradiction", because all cases are false. The disjunction in this table is called a "tautology", because it is true in all cases. This is a topic I will expand on in a later video, because there are some surprising tautologies.

************************************************************************************************************
Yes or No:
- Is a vacuous truth dependent on P?
- Is a vacuous truth dependent on Q?
- Is a trivial truth dependent on P?
- Is a trivial truth dependent on Q?
- Are tautologies also true?

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
