### ISSUE TITLE
Discrete Mathematics 23: Truth Tables 2 (Contraposition & Biconditionals)

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#136]
Hello, world! Shawn Grooms here again with FreeCodeCamp. This is the second video on truth tables. This video will include the concepts of conversion, inversion, contraposition and biconditionals.

We will start again by creating a basic truth table with a single implication.
[P]---[Q]---[P==>Q]
T------T---------T
T------F---------F
F------T---------T
F------F---------T

Defintion of conversion:
The conversion of the implication P==>Q, is Q==>P.
*Note*: This is not the same thing as the negation of P==>Q.
[P]---[Q]---[P==>Q]---[Q==>P]
T------T---------T------------T
T------F---------F------------T
F------T---------T------------F
F------F---------T------------T

Definition of inversion:
The inversion of the implication P==>Q, is ~P==>~Q.
[P]---[Q]---[P==>Q]---[~P==>~Q]
T------T---------T-------------T
T------F---------F-------------T
F------T---------T-------------F
F------F---------T-------------T

Definition of contraposition:
The contraposition of the implication P==>Q, is ~Q==>~P.
*Note*: Contraposition is simply the conversion, of the inversion, of P==>Q!
[P]---[Q]---[~P]---[~Q]---[~Q==>~P]
T------T-------F-------F--------T
T------F-------F-------T--------F
F------T-------T-------F--------T
F------F-------T-------T--------T

Defintion of biconditional:
A biconditional is the conjunction of an implication and its conversion.
i.e. P==>Q && Q==>P
[P]---[Q]---[P==>Q]---[Q==>P]---[(P==>Q)&&(Q==>P)]
T------T---------T------------T----------------------T
T------F---------F------------T----------------------F
F------T---------T------------F----------------------F
F------F---------T------------T----------------------T

******************************************************************************************************
Pending questions.

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
