### ISSUE TITLE
Discrete Mathematics 25: Truth Tables 4 (Fallacies)

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#139]
Hello, world! Shawn Grooms here with FreeCodeCamp. This video will introduce the concept of fallacies, and is the final video on truth tables. Are you sick of truth tables yet?

A fallacy is an implication that, at face value, appears to be a tautology, but isn't. Now, we don't care what anythin appears to be at face value! In mathematics, if you don't prove that an implication is true than it is irrelevant, because you have neither proven or disproven the given implication. So, when in doubt, prove the implication with a truth table. Eventually you will become proficient enough that you don't have to write out basic truth tables. However, if you were to submit a paper in either mathematics or computer science, you will be required to prove whatever you are submitting.

So again, a fallacy is an implication that appears to be a tautology, but isn't, which is to say that sometimes the implication is true and sometimes it is false.

The two most common fallacies are:
- Fallacy of the converse: [(P==>Q) && Q] ==> P
- Fallacy of the inverse: [(P==>Q) && ~P] ==> ~Q

I will construct truth tables for these in the video.

The next video is the last one on the subject of logic, and I will conclude with something called Boolean Zen. I learned this term from a book by Marty Stepp and Stuart Reges called, "Building Java Programs". If you are every interested in learning Java Programming, I highly recommend this book! It teaches you computer science fundamentals and how to program in Java at the same time. See you in the next video.
****************************************************************************************************************
Yes or No:
- Are there too many videos on truth tables?
- Do you feel you can efficiently construct a truth table?
- Is it alright to assume something is true when submitting a paper/work? (no)
- Is it alright to assume something basic is true when you are working alone? (yes)
- Should you assume anything to be true? (no)
- The converse of P==>Q is Q==>P. (yes)
- The inverse of P==>Q is ~Q==>P. (no)

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
