### ISSUE TITLE
Proposed Series: Discrete Mathematics

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#14]
-- = Script not yet completed
 /  = Script submitted and ready to record
X  = Video is being recorded & edited
√  = Video has been finished and uploaded

√ Discrete Mathematics: Tips for Learning
√ Discrete Mathematics: What Is Discrete Mathematics?
√ Discrete Mathematics: Introduction to Sets
√ Discrete Mathematics: Set Operators
X Discrete Mathematics: Associative & Commutative Laws
X Discrete Mathematics: Distributive Law

Proposed topics below this line are tentative, so ignore the numbering.

******************************************************************************************************************

Sets
	/	Discrete Mathematics 12: Subsets & Supersets
	/	Discrete Mathematics 13: Powerset (Maximum Subset)
	/	Discrete Mathematics 14: Complements
	/	Discrete Mathematics 15: Examples (Complements)
	/	Discrete Mathematics 16: DeMorgan’s Laws
	/	Discrete Mathematics 17: Examples (DeMorgan’s Laws)

Logic
	/	Discrete Mathematics 18: Statements
	/	Discrete Mathematics 19: Negations
	/	Discrete Mathematics 20: Conjunctions & Disjunctions
        /	Discrete Mathematics 21: DeMorgan's Law & Logical Equivalence
	/	Discrete Mathematics 22: Implications
	/	Discrete Mathematics 23: Cases & MN-Rule
	/       Discrete Mathematics 24: Truth Tables 1 (Trivial &  Contradiction)
	/	Discrete Mathematics 25: Truth Tables 2 (Contraposition & Biconditionals)
	/	Discrete Mathematics 26: Truth Tables 3 (Tautologies)
	/	Discrete Mathematics 27: Truth Tables 4 (Fallacies)
	/	Discrete Mathematics 28: Boolean Zen

Combinatorics
	/	Discrete Mathematics 29: What is Combinatorics?
	⁃-	Discrete Mathematics 28: Factorials & Complexity 101 (compare 3! vs. 10!)
	⁃-	Discrete Mathematics 29: Permutations & Combinations
	⁃-	Discrete Mathematics 30: Examples (Permutations & Combinations)
	⁃-	Discrete Mathematics 31: Applicable Bonfire

Defining Algorithms
        ⁃-	Discrete Mathematics xx: What is a function?
	⁃-	Discrete Mathematics 46: Algorithms as Functions
	⁃-	Discrete Mathematics 47: Examples (Translating Code to Algorithms 1)
	⁃-	Discrete Mathematics 48: Examples (Translating Code to Algorithms 2)
	⁃-	Discrete Mathematics 49: Comparing Runtime 1
	⁃-	Discrete Mathematics 50: Comparing Runtime 2

Asymptotic Notation
	⁃-	Discrete Mathematics 51: What is Asymptotic Notation?
	⁃-	Discrete Mathematics 52: Big-O
	⁃-	Discrete Mathematics 53: Examples (Big-O 1)
	⁃-	Discrete Mathematics 54: Examples (Big-O 2)
	⁃-	Discrete Mathematics 55: Big-Ω
	⁃-	Discrete Mathematics 56: Examples (Big-Ω 1)
	⁃-	Discrete Mathematics 57: Examples (Big-Ω 2)
	⁃-	Discrete Mathematics 58: Big-Θ
	⁃-	Discrete Mathematics 59: Examples (Big-Ω 1)
	⁃-	Discrete Mathematics 60: Examples (Big-Ω 2)

MAY BE REMOVING THE TOPICS BELOW, AS THEY MAY CAUSE MORE HARM THAN GOOD.
***************************************************************************************************

Relations
	⁃-	Discrete Mathematics 35: Cartesian Products
	⁃-	Discrete Mathematics 36: What is a Relation?
	⁃-	Discrete Mathematics 37: Symmetry & Anti Symmetry
	⁃-	Discrete Mathematics 38: Transitivity & Reflexivity
	⁃-	Discrete Mathematics 39: Tying Relations Together

Functions
	⁃-	Discrete Mathematics 40: Functions & Inverse Functions
	⁃-	Discrete Mathematics 41: Injective & Surjective Functions
	⁃-	Discrete Mathematics 42: Surjective Functions
	⁃-	Discrete Mathematics 43: Composition Functions
	⁃-	Discrete Mathematics 44: Image of Functions
	⁃-	Discrete Mathematics 45: Pre-image of Functions

Proofs - TBD

**Comment by SEGrooms** [comment]
@brianamarie , how on earth did you add the label?

**Comment by brianamarie** [comment]
I think I have special admin access to this repository. :)

**Comment by SEGrooms** [comment]
:+1: OH! That makes a lot more sense. I was going crazy trying to find it.

**Comment by SEGrooms** [comment]
My original plan was to complete the propose hikes in groups, but that didn't work out. It is much easier for me to write a script in pieces than record a video (e.g waiting in line, or just simply thinking about the subject).

**Comment by brianamarie** [comment]
Whatever process works for you works for me. I will add these to the readme so anyone can quickly see what is going on.

**Comment by brianamarie** [comment]
Actually, before I do that, @SEGrooms do you have any ideas about where you think these videos would fit best in the current order listed on the readme? It may even be best to split the categories you've listed up to be between other categories. I could put them someplace, but since I don't know as much about the content as you do, I'd be making more of a guess. Any ideas?

**Comment by SEGrooms** [comment]
@brianamarie I would recommend placing this before Big O notation, and I will link to applicable hikes if I make a connection. So far I have only linked one hike to my scripts, which Computer Basics 5 to Discrete Mathematics 21. Logic section is complete!

**Comment by SEGrooms** [comment]
I am removing the division algorithm from discrete mathematics, and starting another series of hikes called Basic Number Theory, or Number Theory for Programmers. It is an important concept, and the gift that keeps on giving.

**Comment by brianamarie** [comment]
That sounds great. Thanks @SEGrooms

**Comment by SEGrooms** [comment]
The introduction is now complete! @brianamarie , please refer to this list for official titles of the videos. @jameswinegar and I rearranges some things for the scripts, so this is the source of titles.

**Comment by QuincyLarson** [comment]
@SEGrooms By the way, I love your notation system. I propose we use this on all our video challenges.

**Comment by SEGrooms** [comment]
Thank you @QuincyLarson , the check mark is actually a square-root sign. For mac, just hit option+v.

**Comment by atjonathan** [comment]
@SEGrooms, are these challenges finished or is there more to add?

**Comment by SEGrooms** [comment]
These topics have been split into seperate issues, so they are easily analysed on waffle.
