### ISSUE TITLE
Discrete Mathematics 26: Boolean Zen

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#140]
*Have zen-like music in the background*

Hello, world! Shawn Grooms here again with FreeCodeCamp. I am going to be explaining a topic I introduced at the end of the last video, boolean zen.

In simplest terms, boolean zen is finding the most comprehensive and simplest way to code using booleans.
e.g. Consider a function in Javascript that returns a boolean value:

function boolZen(int n){
if( !(n > 5 && n < 14)){
return true;
}else{
return  false;
}

To achieve boolean zen, I would first start by using DeMorgan's Laws on the if test in order to make the code more readable. Some of you may be thinking, why would I do this? The easiest answer is that if you work as a programmer you will work with other programmers. So, if your code is not easy to read right away, it will be frustrating for others and prone to errors.

function boolZen(int n){
if(n <= 5 || n >= 14)){
return true;
}else{
return  false;
}

Next, do you know what the default value of a boolean function is? Boolean functions will return a default value of true. So, unless you tell the boolZen to return false, it will always return true. This isn't a *problem* in our function, but we can easily simplify our code even more. If our function is true by default, why should we test for truth? Shouldn't we test for falsity instead? If we do, we can remove some code, which will make our program run faster and use less energy. You may be thinking this is insignificant, and in this scenario it is, but if you had to call this function a billion times it could add up to a lot of time, energy, and/or money wasted. So here is the remedy:

function boolZen(int n){
if(n > 5 || n < 14)){
return false;
}

Finally, and this one is more personal preference, I would change the test once more. Imagine two number lines like this:
n---(n-1)------8---7---6
------(-1)---0------(n-1)---n------11---12---13
For me, it is hard to take away valuable information, but it is what I imagine based on the inequalities. So, I would change the code accordingly:

function boolZen(int n){
if(5 < n || n < 14)){
return false;
}

I can now picture a number line much easier with n plotted somewhere between 5 and 14.
i.e. 6---7---8---9---10---11---12---13
Now if n = 8, the number line is as such:
i.e. 6---7---n---9---10---11---12---13
and boolZen returns false.

*****************************************************************************************************************
Yes or no:
- Is the final code easier for you to read?
- Can you think of code in which you will use this concept?
- Are you excited to continue onto the new subject of combinatorics?

**Comment by SEGrooms** [comment]
@brianamarie will the swiping left and right app only be concerned with the camper trynig to find the correct answer? Or, would you appreciate survey questions like this? Because, I can't think of applicable swiping questions for this topic.

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the script
