### ISSUE TITLE
Hikes: Binary Numbers

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/hikes#147]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3074

**Comment by brianamarie** [comment]
@SEGrooms do you think this would be a topic/video that should fit into the math videos you're making, or do you think they'd fit better elsewhere?

**Comment by SEGrooms** [comment]
I could easily tie this into Basic Number Theory 1: The Division Algorithm

**Comment by SEGrooms** [comment]
The short answer is yes. I am creating propose topics in number theory. Carl Friedrich Gauss (mathematical rockstar) called number theory, "The queen of mathematics". The topic seems much simpler than it is, so I will refrain from going into as much depth as discrete mathematics.

**Comment by SEGrooms** [comment]
https://github.com/FreeCodeCamp/hikes/issues/152

**Comment by brianamarie** [comment]
Sounds good, thank you.
