### ISSUE TITLE
Proposed Series: Number Theory Applications

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#152]
-- = Script not yet completed
 /  = Script submitted and ready to record
X  = Video is being recorded & edited
√  = Video has been finished and uploaded

******************************************************************************************************

These are propose hikes for Number Theory Applications. This is not a complete list, and I will be adding more topics as they randomly pop into my head.

*********************************************************************************************************
-- The Fundamental theorem of arithmetic
-- What is Prime factorization?
-- Testing for primes numbers(6k+1, 6k+5, √n)
-- What is the division algorithm?
-- Comparing base-n numeral systems.
-- Representing all numbers in binary
-- How do computers represent everything in binary?
-- Computers *don't* have to use binary!
-- Why do computers use binary?
-- How do computers use binary?
-- What is floating point precision?

**Comment by matthras** [comment]
Could possibly include something on floating point precision once you've fleshed out 'binary representations of numbers in a computer' a bit more. Pretty sure most people aren't aware that computers can still make calculation errors with very large numbers or numbers with many decimal places.

**Comment by SEGrooms** [comment]
Sounds good @matthras . Feel free to create some scripts if you want :)

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with these titles into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document

**Comment by atjonathan** [comment]
@SEGrooms, are you working on scripts for this series?

**Comment by SEGrooms** [comment]
@atjonathan yes, however I giving the discrete mathematics series most of my time, as I believe it is most important. This series originated from me thinking of topics that would complement the discrete math series and/or the scripting challenges.

**Comment by SEGrooms** [comment]
series has been split into individual issues for waffle.
