### ISSUE TITLE
Video Challenge Quiz: Computer Basics: Intro to Binary Code - Question 3

### ISSUE THREAD

**Issue by highlanderkev** [FreeCodeCamp/hikes#162]
> Question 3
> There are some things which cannot be translated into binary.
> Current Correct Answer: False

### Issue:
Question/Answer does not take into account Quantum States and the theoretical basis for quantum computing.

**Comment by brianamarie** [comment]
@highlanderkev Thank you for bringing this up! Much like this question, I personally had not taken Quantum States or the theoretical basis for quantum computing into account. :)

Do you think this question would be more accurate and appropriate?
T/F: There are some common data types that cannot be translated into binary. 
(F, All common data types can be translated into binary. Unless you're dealing with Quantum States and the theoretical basis for quantum computing, the data can break down to binary.)

**Comment by highlanderkev** [comment]
@brianamarie No problem! 

I think the reason I got tripped up by this question is the fact that it is a double negative to get to a positive answer (cannot + false = everything can be translated into binary except for this one exception).
I would think it would be better to just reverse it into a truthful statement like below.

Question: All common data types, with the exception of quantum states, can be translated into binary.
Answer: T, All common data types can be translated into binary. Unless you're dealing with Quantum States and the theoretical basis for quantum computing, the data can break down to binary.

Either way works so long as it is being acknowledge and taken into account. 

Thanks!
