### ISSUE TITLE
Wording error on "Computer Basics: Measuring Data Speed"

### ISSUE THREAD

**Issue by elliottleclaire** [FreeCodeCamp/hikes#167]
http://www.freecodecamp.com/videos/computer-basics-measuring-data-speed

The fourth sentence down it says "_Data speed, unlike data size, is usually measured in bits per second, whereas size is usually measured in **bits**_.". 

It's supposed to say "Data speed, unlike data size, is usually measured in bits per second, whereas size is usually measured in **_bytes_**.".

**Comment by brianamarie** [comment]
Fixed and submitted a PR. Thank you @elliottleclaire :)

**Comment by elliottleclaire** [comment]
No problem :D
