### ISSUE TITLE
TV "bugs"/logos for videos

### ISSUE THREAD

**Issue by brianamarie** [FreeCodeCamp/hikes#168]
Per suggestion of @dapperAuteur 

Could/should we add a small logo on the bottom of videos? More info here
https://linux.ucla.edu/~phaethon/misc.crap/tv/

@Rybar and @Septimus, thoughts?

**Comment by Septimus** [comment]
I don't think that is necessary. Youtbe already provides a title, channel name, and many suggestions for videos that are on the same channel. I think the thumbnail images on the videos should be enough to allow people to identify that this is a freecodecamp video but I don't think we'll need any sort of overlay logo throughout the duration of a video.

**Comment by brianamarie** [comment]
I'm with Wes on this for now. We can possibly revisit this in the future.
