### ISSUE TITLE
Discrete Mathematics 13: Complements

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#17]
Hello world! It's Shawn Grooms again, and I am here to talk about complements. I'm not here to talk about compliments, but I would like to thank you for watching this video! Now, this is a very important and simple concept, but that doesn't mean it is easy. For this topic, if everything doesn't make sense right away, rewind. I understand this is contrary to what I recommended in Discrete Mathematics 1, but I believe you would benefit more from moving on to the next video and walking through examples.

Let A be some set. The complement of A is everything not in A, and denoted ~A or A-bar. Now as you let that sink in, notice some of the subtleties of that statement.

e.g. Let B = set of negative integers. Then what is the complement of B? If you said the positive integers (natural numbers), you're wrong. If you were really thinking about the question then you may have said the whole numbers, but you're wrong too!

So why is this? This brings attention to the notion of the "universal set" which is usually denoted by a *fancy U*. If we let U = {..., -2, -1}U{1, 2 , 3,...},  then ~B = *naturals* . Likewise, if we let U = *integers*,  then ~B = *whole numbers*. But, we didn't specify our universal set! Which brings me to my point. If the universal set is not explicity defined, it is assumed to be the real numbers. So in this problem ~B = {x : x *not element of* negative integers} = {x : x *element* of ~B}.

Alright, if you understand most of this video, please see the next one!

******************************************************************************************************************
I would love some feedback on this one, because this is a concept that seem obvious until you are required to really think about the questions being asked. When I first learned this concept I went from 90% confidence to 20% confidence up to 100% confidence. Now it's at the point where a lot of it is obvious to me, so I need someone else to reassure me that it's clear.

**Comment by brianamarie** [comment]
I think the best way to clarify this is with multiple examples that each define different universal sets, sets like B above, and different compliment sets. Show (more than twice) how the process of defining universal sets matters when finding compliments of other sets. 

Not sure if this is the feedback you were looking for - I'm still trying to soak up this information as a beginner. :)

**Comment by SEGrooms** [comment]
Thank you for the feedback @brianamarie , it's always appreciated :+1: I thrive on it! If you look at the next script it should help :)
