### ISSUE TITLE
Statistics/Probability Hikes Summary

### ISSUE THREAD

**Issue by matthras** [FreeCodeCamp/hikes#170]
At the moment I'm trying to figure out the order/segregation of topics and tailoring it for FCC's audience, so there may be some shuffling to happen. Suggestions and any topics I may have missed are always welcome, as it'll take me a while to go through all the secondary school/university resources I have.

## Statistics

- What is Statistics?
- Mean
- Median
- Mode
- Mean vs Median vs Mode
- Variance
- Standard Deviation

### Hypothesis Testing

- Null Hypothesis
- p-value
- A Note on Significance
- Type I & Type II Errors

- What is a t-test?
- One-tail t-test
- Two-tail t-test

- ANOVA (Analysis of Variance)

## Probability

- What is Probability?
- Flipping a Coin and Rolling a Die
- Sample Space & Events
- [Optional] A Review on Set Notation
- Mutually Exclusive & Exhaustive Events
- Basic Probability Axioms
- Conditional Probability
- Conditional Probability Example 1 (Positive Relation)
- Conditional Probability Example 2 (Negative Relation)
- Conditional Probability Example 3 (Independent)
- Independent Events (not to be confused with mutually exclusive)
- Bayes Theorem

- What is a Random Variable?
- Discrete & Continuous Random Variables

### Probability Distributions

- What is a Probability Distribution?
- Discrete & Continuous Distributions

#### Discrete Probability Distributions

- Probability Mass Function (pmf)
- Uniform Distribution (Discrete)
- Binomial Distribution
- Geometric Distribution
- Negative Binomial Distribution
- Hypergeometric Distribution
- Poisson Distribution

#### Continuous Probability Distributions

- Probability Density Function (pdf)
- Uniform Distribution (Continuous)
- Poisson Distribution
- Exponential Distribution
- Gamma Distribution
- Normal Distribution

Covariance
Correlation Coefficient

### Stochastic Processes

- What is a Poisson process?
- What is a Markov chain?
- What is Queueing Theory?

**Comment by jameswinegar** [comment]
Some to add

* Stochastic Processes
* M/M/1/K queues
* Networks
* Moments (and their extensions)
* Symmetric distributions
* Cumulative Distribution Function
* A few Integral discussions (very high level)
* Can use median as an example of an integral that would be useful for continuous variables

Should remove the n-sigma rules and bring them up after talking about symmetric distributions in general

**Comment by matthras** [comment]
Thanks, James. I might make 'Stochastic Processes' a separate category to accommodate Markov chains, Poisson processes, queueing theory and everything following on from that, depending on how many topics we end up exploring.

**Comment by brianamarie** [comment]
This list looks great, very thorough. Since the topics are more on the abstract side, my only note is to try to include how each topic correlates to web development or javascript in as practical of terms as possible. :) Thank you for your work on this.

**Comment by SEGrooms** [comment]
Awesome Matthew! Glad to see you're making progress!

**Comment by brianamarie** [comment]
Hello @matthras! 👋 How's it going with these? 

I'd ❤️  to see these incorporated into our current [README.md](https://github.com/FreeCodeCamp/hikes/blob/master/README.md) with a pull request. Is this something you'd be up to helping with?

**Comment by brianamarie** [comment]
### So you want to help with this issue? Great! Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site

**Comment by matthras** [comment]
I've been utterly swamped with real life. Happens when you're teaching at three/four tertiary institutions! Thankfully the semester's over now so I've got time to get things going.

I've got some raw footage recorded for the 'What Is Statistics?' video, just need to edit it together. Definitely hoping to make some progress over the next two months before the next semester begins!

**Comment by atjonathan** [comment]
@matthras Awesome :tada:

**Comment by brianamarie** [comment]
> Happens when you're teaching at three/four tertiary institutions!

😮  Holy moly, no kidding you've been swamped! 


> I've got some raw footage recorded for the 'What Is Statistics?' video, just need to edit it together.

Fantastic! As soon as you have it edited, we'd ❤️  to see it! I'm sure @jameswinegar and @SEGrooms would love to see it, too. 😄

**Comment by brianamarie** [comment]
@matthras ^^ I'm sorry, I forgot to mention you in the comment above! 😊

**Comment by QuincyLarson** [comment]
I'm closing this issue and opening individual issues for all the topics mentioned here.
