### ISSUE TITLE
Organize README to reflect accurate overview

### ISSUE THREAD

**Issue by brianamarie** [FreeCodeCamp/hikes#174]
If anyone is looking for an opportunity to contribute with minimal coding involved, the readme for this repo isn't in great shape.

It would be idea for the readme to reflect the current status of videos in five tiers.
1. Help wanted
2. Pre-production (script has not yet complete, but video has user assigned to start the process)
3. Production (script is complete and has been looked at by other team members, video is not yet complete)
4. Post-production (video has been recorded)
5. Deployed & live

**Comment by alistermada** [comment]
I'd like to help out with this. For the following example, I added the link to the challenge in FCC for deployed videos and the link to the GitHub issue for other videos (if available). What do you think?

---
## Help Wanted
Video | Category
--- | ---
[What does 'Open Source' mean](https://github.com/FreeCodeCamp/hikes/issues/132) | Computer Basics
Arrays | Data Structures
[Introduction to Markdown](https://github.com/FreeCodeCamp/hikes/issues/21) | Tools

## Pre-production
Video | Category | User assigned
--- | --- | ---
[some video] | [some category] | [some user]

## Deployed & Live
Video | Category
--- | ---
[The 4 Basic Parts of a Computer](https://www.freecodecamp.com/videos/computer-basics-the-4-basic-parts-of-a-computer) | Computer Basics
[More Computer Hardware](https://www.freecodecamp.com/videos/computer-basics-more-computer-hardware) | Computer Basics

**Comment by josectello** [comment]
@alistermada Perhaps another option could be to create a third (or fourth) category to a single list of Hikes which would specify the current state of the hike. If the *Help Wanted* column is marked no, then maybe the assigned user can be insert in the same cell (below "No")?
Just throwing ideas out there.

| Video              | Category           | Help Wanted  |
|:-------------------|:----------------------|:-------------------|
| [some video]  | [some category] | [yes/no]          |

**Comment by brianamarie** [comment]
@alistermada @josectello I like all of these ideas. It's all better than the current state! 👍

**Comment by alistermada** [comment]
@brianamarie I notice that there have been a few scripts submitted/suggested that you've approved. Does that mean that particular video officially has a user assigned (the scriptwriter)? Will the scriptwriter always be the same person as the one tasked with recording the video?

@josectello I like where you're going with this. Building on your idea, the assigned user (or user assigned?) column could either contain the user's name or "Help Wanted". There would be only two lists, one for deployed videos and one for upcoming videos.

Two alternatives for the list of upcoming videos:
---

### Upcoming Videos

Video | Category | Assigned User(s) | Script? | Recorded?
--- | --- | :---: | :---: | :---:
[What does 'Open Source' mean](https://github.com/FreeCodeCamp/hikes/issues/132) | Computer Basics | Help Wanted |  :white_medium_square: |  :white_medium_square:
I've got a script! | [some category] | [user] | :white_check_mark: | :white_medium_square:
I'm in post-production! | [some category] | [user] | :white_check_mark: | :white_check_mark:
### Upcoming Videos (alternative)

| Video | Category | Assigned User(s) | Status |
| -------------------------- | --- | :---: | --------- |
[What does 'Open Source' mean](https://github.com/FreeCodeCamp/hikes/issues/132) | Computer Basics | Help Wanted |  :white_medium_square: Script </br> :white_medium_square: Recorded 
I've got a script! | [some category] | [user] | :white_check_mark: Script </br> :white_medium_square: Recorded
I'm in post-production! | [some category] | [user] | :white_check_mark: Script </br> :white_check_mark: Recorded

Thoughts? 

Note: For the alternative table, long video titles would have to be broken up with `</br>` tags to ensure that the status column's width isn't affected, as it would break the checklist's alignment.

**Comment by josectello** [comment]
@alistermada I definitely like the second (alternative) table. Looks pretty sharp.

**Comment by brianamarie** [comment]
✨💖✨ Wow @alistermada, I love it! ✨💖✨ I agree with @josectello, I think the second table is a little bit more clear. Go forth and organize the README! 🚢

**Comment by alistermada** [comment]
Minor update: I've finished the deployed videos table and I'm currently working on the upcoming videos table.

@brianamarie The upcoming videos listed under "Computer Basics" are linked to issues labeled "Computer Science". A lot of these topics seem to be outside of what most would consider to be computer basics. 

I suggest relabeling some of these to "Computer Science". What do you think?

- Computer Basics: What does 'Open Source' mean?
- Computer Basics: How Does RAM Work?
- Computer Basics: What Are Ports?
- Computer Basics: What is Garbage Collection?
- Computer Basics: What is Just-In-Time Compilation?
- Computer Basics: What is Assembly Language?
- Computer Basics: What is An Interpreter?
- Computer Basics: Compiled vs Interpreted Languages
- Computer Basics: What is a Compiler?
- Computer Basics: What is an Evented Server?
- Computer Basics: What Are Threads?
- Computer Basics: What is an Embarassingly Parallel Algorithm?
- Computer Basics: What is an Algorithm?
- Computer Basics: Packets and Data Frames
- Computer Basics: What is a Matrix?
- Computer Basics: Dictionary
- Computer Basics: What is Object Oriented Programming?
- Computer Basics: How Basic Error Handling Works
- Computer Basics: What is an SDK?

**Comment by brianamarie** [comment]
@alistermada I see what you mean, and I agree. I think the ['Open Source' video](https://www.youtube.com/watch?v=o0Pi0966BOM) could still fit into the Computer Basics category, but all of the others could fall into Computer Science pretty well. 

Any thoughts on this @SEGrooms @jameswinegar @dapperAuteur?

**Comment by SEGrooms** [comment]
@brianamarie I think that anything involing algorithms belongs in computer science. In terms of how hardware works, I don't know enough to have an opinion. However, I think at this point we should keep making videos and continue working on the order as the videos are produced.

**Comment by alistermada** [comment]
Alright, I'll leave it as Computer Basics for now.
