### ISSUE TITLE
Proposed Series: Linear Algebra

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#176]
HELP WANTED!!

I hope to start working on this in the summer, but if someone beats me to it no worries
************************************************************************************************************

-- = Script not yet completed
/ = Script submitted and ready to record
X = Video is being recorded & edited
√ = Video has been finished and uploaded

-- Vectors
-- Matrix Algebra
-- Systems of Linear Equations
-- Vector Spaces
-- Linear Mappings
-- Bases
-- Inner Product Spaces & Orthogonality
-- Determinants
-- Eigenvalues & Eigenvectors
-- Canonical Form
-- Dual Spaces

**Comment by SEGrooms** [comment]
Hey @jameswinegar I think this is a good guide for the linear algebra series.

**Comment by jameswinegar** [comment]
@SEGrooms I would start with vectors completely, then expand into matrices and borrow the concepts of the vector space. We can probably leave off dual spaces, and add projections and spectral theorem concepts. Maybe define what a metric is as well when discussing inner product spaces.

**Comment by erictleung** [comment]
@SEGrooms Maybe add spans to the series too, as suggested by #80.

**Comment by brianamarie** [comment]
### So you want to help with this issue? Great! Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site

**Comment by jameswinegar** [comment]
Sean and I are meeting next week while he is moving. Should be working on these again soon.

**Comment by SEGrooms** [comment]
This video has been split into individual issues for waffle.
