### ISSUE TITLE
Discrete Mathematics 14: Examples (Complements)

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#18]
Hello world! It's Shawn Grooms here with two examples of complements and some challenge problems.

Let A = {alpha, beta, gamma}, B = {beta, delta}, C = { alpha, beta, delta}, U* = {alpha, beta, gamma, delta}

This video will include the following examples and/or chalenges:
- ~A
- ~B
- ~C
- ~U*
- AU~B
- A∩~B
- U*∩~C
- BUU*

**************************************************************************************************************
Examples will be shown using both venn diagrams and exlusively using set notation.

**Comment by brianamarie** [comment]
Haha! This is exactly what I just commented on. In the previous video where there aren't examples, I'd clarify by saying very simply at the end what users need to remember. In as few words as possible say it's okay if they aren't totally solid, but they need to take away '' and ''. Reassure them there will be examples soon to help clarify.

**Comment by SEGrooms** [comment]
haha! Just did the same thing you did. That's a good idea, because I believe it is a concept best understood through example.
