### ISSUE TITLE
Reorganizing the hikes repository

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/hikes#188]
- [x] Filter through and get rid of old and unattended issues.
- [x] Get rid of the [Video Challenge Tracking Doc](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) and instead opt for using github issues and labels out of the box.
- [x] Confirm the workflow from start to finish for creating content.
- [x] Create a Issue Template with new workflow checklist.

cc/ @FreeCodeCamp/hikes, @Septimus, @brianamarie, @QuincyLarson

**Comment by brianamarie** [comment]
Thank you so much @atjonathan, I think this is ✨! 

Should/can we also include an issue template with the workflow checklist?

**Comment by atjonathan** [comment]
@brianamarie Yeh, defiantly! Adding that now!

**Comment by atjonathan** [comment]
Finished!
