### ISSUE TITLE
Discrete Mathematics 15: DeMorgan's Laws

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#19]
Hello World! Shawn Grooms here giving a compliment, not a complement, to Professor Augustus De Morgan for his excellent laws! If this video is too difficult to follow then rewatch video on Associative & Distributive Laws. In addition to my video on Complements.

DeMorgan's Laws:
1) The complement of a union is the intersection of the complements.
2) The complement of an intersection is the union of the complements.

e.g.  ~(AUB) = ~A ∩ ~B
e.g.  ~(A∩B) = ~A U ~B

That's it! Short simple and to the point. Keep this in mind as we move into talking about logic. You will find that this is one of the best ways to drastically simplify your code when using boolean tests. Also, check out the next video for more complex examples and challenges.

*********************************************************************************************************************
To my surprise, this will probably be my shortest video. However, I will still include an example video.

**Comment by brianamarie** [comment]
If the content of this is short enough to explain, it would be ok to include examples within this same video.

**Comment by SEGrooms** [comment]
Yeah, that seems pretty obvious now that you say it.
