### ISSUE TITLE
Discrete math hikes

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/hikes#2]
Camper @jorgon1022 recommended we create a series of Hikes on concepts in discrete math. Here's a series for reference: https://www.youtube.com/watch?v=MmzJF2L_5PA

**Comment by brianamarie** [comment]
I agree that discrete math concepts will be helpful to writing algorithms and other tasks necessary as a developer. 

Not knowing much about discrete math myself, my concern is that the topics covered in those videos are too complex to cover effectively in 3 minute videos. 

If I could see an example, I may be able to better understand what you're envisioning. I'd like to see an example of a script or video that would fit the shorter, more beginner friendly format of the current hikes. @jorgon1022 is this something you'd be comfortable doing?

**Comment by jorgon1022** [comment]
I'm happy to help with what I can. Would you like me to look for some
videos that are more beginner friendly?

**Comment by brianamarie** [comment]
Yes, please! Thank you @jorgon1022. 

If you feel so inclined, I'd love to see a script for something you're envisioning. 

Here is an example of how I wrote scripts. This link has short scripts for every video in the JS lingo unit, and will be here on github soon. https://docs.google.com/spreadsheets/d/1ekFnD9yxbAF0Bl7m6ptQo3PfIaqj1Tl8HVV9k4QJvTM/edit?usp=sharing

**Comment by SEGrooms** [comment]
I believe the best place to start is with the introduction to sets, and then move into logic and truth tables.

**Comment by SEGrooms** [comment]
Hey @brianamarie I'm currently producing a google-sheet based on the format of the one you posted above. I don't believe hikes are the correct method for teaching campers how to truly analyze algorithms. However, hikes are perfect for teaching them how to (sometimes drastically) simplify their code. The best subject to introduce first would be sets and then move into truth tables. I will do my best to break the content down into simplest form for the videos.
https://docs.google.com/spreadsheets/d/1AZxNBQ7aDjSocXRK5ozwzg3c1e2Ct7Is6tapLBuM98M/edit#gid=0

**Comment by brianamarie** [comment]
@SEGrooms I'd love to take a look at your work on the script so far. I have requested access through gmail. Usually, I change the settings so anyone with the link can comment.

**Comment by SEGrooms** [comment]
@brianamarie just did. I thought everyone could already see it. I don't use google docs often.

**Comment by SEGrooms** [comment]
Hey everyone, check out the ReadMe file for videos I will be developing in the coming weeks!

**Comment by SEGrooms** [comment]
Also, check out the new issues I have created. These are the proposed scripts for future videos. I'm just not that familiar with GitHub, so I hope I'm doing stuff correctly.

**Comment by brianamarie** [comment]
@SEGrooms these all look FANTASTIC. I can't wait to see the videos. Are you planning on finishing all of the scripts before you start to record, or going in chunks? 

Additionally, with each video, please write 2-3 true or false questions that you feel check for understanding of the concept(s) covered in that video. These will be tinder style swipe left/right on mobile and aim to keep users engaged every few minutes instead of letting the videos play and not actually listening.

Keep up the awesome work!

**Comment by SEGrooms** [comment]
Well currently it is all kind of just flowing out of my head, so I figured I would keep writing until it stopped. Lol. It's quite easy to write them when you have a general goal and know where to start. Fortunately I know where to start, and my goal is to lay the foundation for campers to understand Big-O notation.

I think what I should do is write the scripts for a section, and then record the videos. This will allow me to adjust the videos if need be. I am concerned, as the topic is quite dense, and I don't want people to run away!

The true or false should be quite easy to set up as well. If need be I can just leave them in the description of the video. When I do end up recording the videos, where should I upload/send them to?

**Comment by SEGrooms** [comment]
@jorgon1022 I discontinued the use of the google sheet, and using GitHub exclusively.

**Comment by brianamarie** [comment]
@SEGrooms I'm not totally sure right now. When I recorded them, I edited them myself and uploaded them directly to YouTube and Vimeo. With more contributors now, I think we need a different and more structured system.

@Septimus, you are now fully in charge of YouTube and Vimeo. What do you think would be the most efficient way of uploading new hikes from different contributors?
