### ISSUE TITLE
Discrete Mathematics 11: Examples(DeMorgan's Laws)

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#20]
Hello, world! This is Shawn Grooms, and we're going to go over some more advanced sets. We'll be playing with DeMorgan's Laws, which will, fortunately, review a lot of material we have covered about sets. I am purposely not defining the given sets. This will require you to really think about commutativity, associativity, complements, and DeMorgan's Laws, rather than simply finding an answer. They are supposed to be challenging, because this is the last video on sets!
 
Examples and challenges covered will include:
- ~(A∩B) = ?
- ~(AUB) = ?
- A∩~(BUC) = ?
- AU~(B∩C) = ?
- ~(AUBUC) = ?
- ~(A∩B∩C) = ?
- (AUB)∩(CUD) = ?
- (A∩B)U(CUD) = ?
- (A∩B)∩(C∩D) = ?
- (AUB)U(CUD) = ?

In the challenges above, you aren't looking for an answer, but rather putting the sets in different forms. If you want, feel free to define the sets and see what happens. Let me know how it goes!

*****************************************************************************************************************
This is the final script or sets, which means time to start filming! Feedback is always appreciated :)

**Comment by brianamarie** [comment]
Woohoo! Have fun filming! If you have any questions, please feel free to ask.
