### ISSUE TITLE
Establishing priorities for Sept 11 all-day filming spree in San Francisco

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/hikes#205]
We need to establish which types of challenges we want to film on [Sunday, September 11 at location TBD](https://www.facebook.com/events/1759008574378819/).

Once we establish this, I can set out to find experts in these various fields who are in the area and could drop by for a few hours to help us.

Here are the tags that currently have video challenges associated with them. I've sequenced them based on my opinion of the demand for them among our community.

- [ ] [User Experience Design](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3A%22UX+Design%22)
- [ ] [Machine Learning](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3A%22Machine+Learning%22)
- [ ] [Working in Tech](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3A%22Working+in+Tech%22)
- [ ] [Computer Science](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3A%22Computer+Science%22)
- [ ] [Statistics](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3AStatistics)
- [ ] [Software Engineering Principles](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3A%22Software+Engineering+Principles%22)
- [ ] [Networks](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3ANetworks)
- [ ] [Agile](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3AAgile)
- [ ] [DevOps](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3ADevOps)
- [ ] [Tools](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3ATools)
- [ ] [Databases](https://github.com/FreeCodeCamp/hikes/issues?q=is%3Aissue+is%3Aopen+label%3ADatabases)

cc: @brianamarie @atjonathan @Septimus 

@segrooms is handling discrete mathematics. (not listed)

@Septimus is handling Bash and Git.

@brianamarie may be in a good position to focus on the remaining computer science issues.

What are your thoughts everyone?

**Comment by Septimus** [comment]
How many of these do we want to pick? By all day you mean 8 hours? 10 hours? 12 hours?

**Comment by QuincyLarson** [comment]
@Septimus yes - I'm hoping we can record for around 12 hours. @brianamarie estimated that, with talking points in hand, each video would take 10 - 15 mins to produce. 
(12 * 60) / 15 = ~50 video challenges

**Comment by Septimus** [comment]
@QuincyLarson @brianamarie Would 10 - 15 minutes be enough to account for mistakes or multiple takes? What about picking 4, 5, 6 of the most important topics and spending the day getting the series perfect? Just throwing ideas out for the production day.

My top 5 picks from that list are:

User Experience Design
Machine Learning
Computer Science
Software Engineering Principles
Networks

**Comment by QuincyLarson** [comment]
@Septimus I agree. A big part of this will be seeing whom we can get to come out and talk. I'd rather have people who have at least some experience in each field so they can speak with some degree of authority. I've reached out to a few people I know here in the Bay Area who are experts in these various topics. 

I think you are definitely well-enough acquainted with Bash and Git, and @brianamarie is well-enough acquainted with CS, but when it comes to UX and ML, it would be nice to find a practitioner.

**Comment by Septimus** [comment]
@QuincyLarson If you can't end up finding anyone for UX after the 11th passes I can work on those too. I read the complete documentation for Material Design, Apples design docs, and then some blogs here and there about general design. Just so you know. ;)

**Comment by QuincyLarson** [comment]
@Septimus awesome. I will keep you posted. The Git and Bash challenges are even higher priority than any of the ones we'll record on Sept. 11 so focus on those first :)

**Comment by SEGrooms** [comment]
@QuincyLarson @Septimus That sounds like one heck of a party! Not sure if you're looking for more input, but here's my two cents.

My top 5 are:
1. UX Design
2. Working In Tech
3. Computer Science
4. Software Engineering Principles
5. Statistics

Although popular, I ommitted machine learning, as I don't believe the prerequisite material has yet been covered. The limited exposure I've had with machine learning was incredibly complex to understand! I had to use a lot of knowledge from linear algebra and statistics. With that said, learning how to use these techniques was easier than understanding why they work.

**Comment by QuincyLarson** [comment]
@SEGrooms Thanks for this feedback. 

Regarding machine learning, our goal would be to try to explain these concepts at a high enough level that anyone could walk away with a rough conceptual idea, even without any prerequisite knowledge.

**Comment by QuincyLarson** [comment]
@brianamarie you mentioned that you might be able to cover some GitHub-specific topics and/or workflows - either yourself or colleague. Is this a possibility for Sept 11?

**Comment by brianamarie** [comment]
> @QuincyLarson @brianamarie Would 10 - 15 minutes be enough to account for mistakes or multiple takes? What about picking 4, 5, 6 of the most important topics and spending the day getting the series perfect? Just throwing ideas out for the production day.

@Septimus 👍  I'm on board! 



> @brianamarie you mentioned that you might be able to cover some GitHub-specific topics and/or workflows - either yourself or colleague. Is this a possibility for Sept 11?

@QuincyLarson Yes! I am more than happy to cover Git and GitHub topics on the 11th. I've spoken with my colleague @hollenberry who won't be available on the 11th, but has availability on Friday, Sept 16th. I could also have some availability that day, but the 11th works better for me. 😄

**Comment by QuincyLarson** [comment]
@brianamarie great - we can prioritize Git and GitHub-specific videos. @Septimus if you haven't started recording the Git videos, perhaps you could do the Bash videos first - then you could do the Git videos if Briana isn't able to get to them in time.

**Comment by QuincyLarson** [comment]
@brianamarie @atjonathan @Septimus @SEGrooms I've reached out to an experienced UX designer and agile coach and they already have a whiteboard + tripod setup in their apartment. So they may be able to record these videos. So I recommend we leave these topics to them for now and focus on other ones on Sept 11. 

I also recommend we switch to using this Waffle board, which will make it easier to visualize the state of various issues: https://waffle.io/FreeCodeCamp/hikes

And finally, I recommend we break each video out into its own distinct issue (rather than having issues with checklists of videos). This will give us more fine-grain control of the issues.

What are your thoughts on this?

**Comment by QuincyLarson** [comment]
@brianamarie @atjonathan @Septimus @SEGrooms what do you think of this proposal? Can we go forward with this? Would anyone be interested in breaking existing list-oriented issues down into individual issues?

**Comment by SEGrooms** [comment]
@QuincyLarson the waffle board is pretty cool. I'll go through the math for programmers label and break the "proposed series" issues into individual issues.

**Comment by QuincyLarson** [comment]
@SEGrooms Awesome! Thanks for doing this. I am really excited to watch the rest of your videos. Your intro video was excellent :)

**Comment by SEGrooms** [comment]
Thank you @QuincyLarson! There is more to come soon :)

**Comment by carl-parrish** [comment]
Software Engineering Principles
User Experience Design
Agile
DevOps 
Tools

**Comment by QuincyLarson** [comment]
@carl-parrish thanks for your input :)

**Comment by brianamarie** [comment]
> what do you think of this proposal? Can we go forward with this? Would anyone be interested in breaking existing list-oriented issues down into individual issues?

I am going to prioritize creating issues for Git/GitHub topics for a short series today 👍

**Comment by QuincyLarson** [comment]
@brianamarie @Septimus @atjonathan @SEGrooms @carl-parrish Quick update:
- I broke all multi-video issues down into individual issues (to make them more compatible with Waffle)
- I added a ton of UX Design and Agile video challenges, some of which @creativejuggernaut will record in her home.
- I recorded this short screencast showing how to use Waffle and explaining (what I understand to be) our workflow for these videos: https://www.youtube.com/watch?v=HOYBSuGeSU0

**Comment by mrpatil007** [comment]
@QuincyLarson actually i cant able to move my card of ethical hacking video

**Comment by SEGrooms** [comment]
@QuincyLarson I'm really interested in the agile series. It is mentioned in a lot of job postings.

**Comment by QuincyLarson** [comment]
@mrpatil007 I've granted you write permission on this repository. Check your email for a confirmation. Then you'll be able add tags to issues (and Waffle cards)

**Comment by QuincyLarson** [comment]
@SEGrooms I recommend you focus on the math challenges (which you are much more qualified to film than the rest of us) first, and we can see how many of the agile videos @creativejuggernaut will be able to film first.

**Comment by SEGrooms** [comment]
@QuincyLarson haha I must reiterate, I don't have the first clue about agile, which is why I'm interested in the series! I have ZERO intention of trying to film the series. I'm more than happy to stick with recording mathematics videos.

**Comment by mrpatil007** [comment]
@QuincyLarson i know this is off discussion but i message you some design of FreeCodeCamp Android application

**Comment by QuincyLarson** [comment]
@SEGrooms haha - indeed. I misunderstood. Yes - I think everyone will benefit from learning a more about agile and project management in general, since we're all likely to work in such environments in the future.

@mrpatil007 OK - cool. I will catch up on Gitter later tonight :)

**Comment by SEGrooms** [comment]
How'd the filming party go???

**Comment by QuincyLarson** [comment]
@SEGrooms it ended up just being three people: @brianamarie, @mpaluru and myself. It was focused and productive. Briana recorded around a dozen git and GitHub focused videos, and Murali recorded five or six networking-focused videos. 

All of the videos were single-take at-the-whiteboard videos between less than 2 minutes (I think one was 2:15).

Murali's iPhone 6 + tripod + lavalier setup worked awesome. We were able to use some nearby lamps to get the lighting right. Overall, it was a productive 6 hours of filming. 

We still have a lot of videos left to film, but we can get these live soon. @mpaluru will upload the videos to Google Drive then get them to @atjonathan for post-production later today :)

Here's the group photo: https://twitter.com/brianamarie132/status/775145637767581696

**Comment by SEGrooms** [comment]
At least you had 3 people! I'm recording again tomorrow, so excited!

**Comment by QuincyLarson** [comment]
@SEGrooms we actually had 22 people signed up to come, but only a few of those people were actually going to record, so we decided to make it a private event. I think we were much more productive as a result.

**Comment by SEGrooms** [comment]
Oh wow, I didn't realize so many people were attending. I'm glad you guys made progress, and looking forward to the new videos. My goal is to complete 17 mathematics videos tomorrow. I don't think that's being too ambitious...we'll see!

**Comment by SEGrooms** [comment]
Either way, I'm sure as heck going to try!

**Comment by QuincyLarson** [comment]
@SEGrooms Awesome! We recorded a new intro video and specifically mentioned math as something our video challenges will cover (along with computer science and software engineering principles). Good luck with the recording!
