### ISSUE TITLE
Test {Insert subject for proposed hike here}

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#3]
@BerkeleyTrue is this how you want us to add content for proposed hikes?

**Comment by brianamarie** [comment]
For proposing new hikes, I think creating a general issue like this is a good place to start. After getting feedback on if it may fit the curriculum, the next steps are to answer a few questions as a team.

- What unit will the hike be a part of?
- If it's a new unit, where will that go linearly? (At this point, add to ReadMe with current status information "in progress")
- Who is writing the script?
- Who will record the video(s)?
- Who will edit and upload the videos? 

It may make the most sense to continue coordination and communication about any given hike in the same issue that it was first discussed, or we may find a better way. 

Does this answer your question @SEGrooms? 

Do you or does anyone else (@BerkeleyTrue @QuincyLarson @shankarkd @jorgon1022) have other ideas about how to streamline this process?

**Comment by BerkeleyTrue** [comment]
LGTM

I'm mostly here to enable you all. My only suggestion would be to keep the process Github central so those who contribute to this repo see there Github activity increase.

**Comment by SEGrooms** [comment]
Sounds goods @BerkeleyTrue. Yes @brianamarie that answers my question thoroughly!
