### ISSUE TITLE
Create Your Own Website

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#459]
#### Name of requested series:
Create Your Own Website

#### Proposed episodes for series:

- How do you purchase a web domain?
- Hosting with GitHub Pages
- Adding code to your site using git/github
- Updating code for your site using git/github
- What is Google Analytics?
- Adding Google Analytics to your site

#### Description of content:
Great! You've progressed through your FCC curriculum, and used your laptop as a pillow hoping to absorb the JS, HTML, CSS, Bootstrap, and jQuery documentation, but how do you actually use it? You probably know how to set up your development on your laptop and view it in the browser, but how do you actually turn that into an accessible website? This series will show you how to set up your own domain that is updatable using version control, rather than static text files. You will be on your way to landing your first front end job in no time! This series will tie in with the git/github series by @brianamarie.

#### Current Status:

- [x] ![01: Help Wanted](https://img.shields.io/badge/Label-01: Help Wanted-000000.svg)
- [ ] ![02: Scripting](https://img.shields.io/badge/Label-02: Scripting-000000.svg)
- [ ] ![03: Recording](https://img.shields.io/badge/Label-03: Recording-000000.svg)
- [ ] ![04: Reviewing](https://img.shields.io/badge/Label-04: Reviewing-000000.svg)
- [ ] ![05: Finalizing](https://img.shields.io/badge/Label-05: Finalizing-000000.svg)

**Comment by SEGrooms** [comment]
I'm still using codepen for my personal portfolio, but I want my own domain name instead. However, finding a reliable _**unbiased**_ source seems to be impossible, as there are thousands of websites wanting you to use their product for your website.

**Comment by QuincyLarson** [comment]
@SEGrooms we do have quite a few Medium articles on how to deploy to your own service, and my honest opinion is having a personal domain is completely over-rated. You have to spend money every year to keep it, and people are unlikely to randomly visit it. By posting content on CodePen, Medium, and other sites, at least you'll get some level of organic traffic.

If you wanted to walk someone through deploying a personal website to a domain, you could do so, but this is very service-specific. You won't be able to avoid choosing a domain registrar and a cloud provider, for instance.

**Comment by SEGrooms** [comment]
Alright, I wasn't sure if it was omitted from the curriculum, because it was unnecessary or more advanced. I figured I would check. I'm convinced, I'll close this one out.
