### ISSUE TITLE
Discrete Mathematics 1: Breathe Easy & Just Rewind - Script

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#6]
Script for my 1st discrete mathematics video.
*******************************************************************************************************************
Hello World! My name is Shawn Grooms. I am a senior mathematics student, and a fellow camper at FreeCodeCamp. I was previously a discrete mathematics tutor at my university, and am now sharing the same knowledge with all of you.

I want to begin by saying that I understand mathematics is a stressful subject for many people. Unfortunately, what happens is someone will hear something, not understand it immediately, panic, and ultimately give up. Trust me, I understand this anxiety better than most! But, I want to remind you that this is a video, not a classroom. So, if you find that you are suddenly lost just pause the video. After you pause, take a deep breath, and rewind to where you last understood what was being explain. It's no problem.

Another thing that a lot of people struggle with is their pride. Please don't let your pride deprive you of your knowledge! Mathematicians will be the first to tell you that mathematics can be very humbling. The problem is that no one likes feeling ignorant, so again people give up before they should. So I will stress again, just relax and rewind the video.

The goal of this series is to teach you the fundamentals of discrete mathematics, and accelerate your ability to develop simple and efficient algorithms. Enjoy!
*******************************************************************************************************************
What do you guys think?

**Comment by shankarkd** [comment]
Hey @SEGrooms, this is a pretty good intro. Its a good introduction and I like the way you are easing folks into the subject. Just want to point out a few things.
1. In the first paragraph, my guess is you meant to say "a Discrete Mathematics major" (you left the 'major').
2. In the second paragraph, I think you meant to say "not understand" instead of "note understand".

I sometimes rely on a browser extension called grammarly (https://www.grammarly.com/). Give it a look.

**Comment by SEGrooms** [comment]
Thanks for the feedback @shankarkd! :+1: And thank you for the link. I may actually use that for my school work as well.

**Comment by shankarkd** [comment]
@SEGrooms you are welcome.

**Comment by jameswinegar** [comment]
Questions
---------------

- Should I rewatch hikes if I have questions? T/F (T)
- What's the best way to study math? MC - Calmly, Anxious, Distracted, Confused (Calmly)

**Comment by SEGrooms** [comment]
Hi @jameswinegar , thanks for the input! :) :+1:  @brianamarie mentioned adding questions after I completed this script, so I will be adding questions to them as I go to record them.

**Comment by SEGrooms** [comment]
This video is now record, edited, and ready for upload!

**Comment by brianamarie** [comment]
Great, just as the other one, send it to me if it will send over email and I'll get the videos uploaded. Thank you for your work on this @SEGrooms :)

**Comment by SEGrooms** [comment]
You're welcome @brianamarie , just sent the first video!

**Comment by brianamarie** [comment]
Vimeo: https://vimeo.com/home/myvideos/page:1/sort:date/format:video
YouTube: https://youtu.be/j1QkEV1nhOI
