### ISSUE TITLE
Discrete Mathematics 2: It's All About The Definitions - Script

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#7]
This video is just tips on learning the material, and resources for extra practice.
*******************************************************************************************************************
Hello world! Shawn Grooms here. This video is to give you a few tips on learning mathematics. The best kept secret to learning mathematics is knowing a little and doing a lot. It may seem like a lot of material at first, but when you realize how much you can do with simple ideas, it will begin to resonate.

So how do you do that? Whenever I present a new idea, linger on that new idea. Even if you believe that you understand the idea at first glance, reread the definition and/or re-watch that segment of the video. I will be introducing definitions as needed. If you can't explain it to yourself out loud, you probably don't understand it fully. Which, as stated in the previous video, is alright. Just rewind, and give it another try.

If that still doesn't work, or if you want a more in-depth look on the subject, check out the link in the description. "The Book of Proof" by Richard Hammock is a free textbook with excellent descriptions, and even more excellent problem sets! I must include that the textbook doesn't solely cover discrete sets, rather mathematics as a whole, but it will still strengthen your understanding of the topics mentioned in the videos. If you want a book specifically on the subject of discrete structures, then check out this other free text book Kenneth Levasseur. However, I believe that if you don't have a history with proofs or discrete mathematics, this text may be too challenging. Best of luck!

http://www.people.vcu.edu/~rhammack/BookOfProof/.
http://faculty.uml.edu/klevasseur/ads2/
*******************************************************************************************************************
Any other good resources/suggestions?

**Comment by SEGrooms** [comment]
This video is now record, edited, and ready for upload!

**Comment by brianamarie** [comment]
Awesome. Will the file size send over email? If so, send it to me at 372bmswift27@gmail.com and I'll get it up to YouTube and Vimeo.

**Comment by SEGrooms** [comment]
I think 150mb is too large to send...

**Comment by brianamarie** [comment]
Gotcha. I think the easiest way would be to upload it to google drive. Once I download it, I'll email you and let you know you can delete it so it doesn't eat up storage. Does that work for you? Thank you for being flexible with this process. If you think of a better way, I'm open.

**Comment by brianamarie** [comment]
Vimeo: https://vimeo.com/150739351
YouTube: https://youtu.be/yPCw7BNGU_o
