### ISSUE TITLE
Discrete Mathematics 5: Elements & Sets

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#8]
Hello World! It's Shawn again. Before we start with the introduction of sets, there are two acronyms I will write frequently. The first is i.e, which is short for id est, and translates from latin as "that is." The second is e.g, which is short of exempli gratia, which translate as "for example." Now onto the mathematics.

I want to first mention the concept of an element. An element is, in simplest terms, anything that isn't nothing. This concept will make more sense soon, but please bear with me for now.
       e.g. 1,2,3,x,y,z, waypoints, bonfires, ziplines.
Don't overthink it! An element is anything that isn't nothing :)

Now, a set is simply a collection of elements, and is usually denoted by a capital letter.
       e.g. A = {1,2,3,}, B =  {x,y,z}, C =  {waypoints, bonfires, ziplines}

Two new symbols I will introduce are as follows:
- symbol: this is called an ellipsis and means "repeat the sequence/pattern indefinitely"
      - e.g. D = {1,2,3,...} = all positive integers
- symbol: "is an element of"
      - e.g. Let E = {q,r,s}, then r *symbol* E, which is read "r is an element of E"

*******************************************************************************************************************
Let me know what you think :)

**Comment by jameswinegar** [comment]
Use an example set where they're not all the same type to enforce that you don't need to have a set consist of the same type of elements.  {1,q, waypoints, +, smiley face }.

Include empty set,  {}

Questions
---------------

- Can a set contain no objects? T/F (T)
- What's the maximum number of objects a set can have? MC - 2,4,7, infinite (infinite)
- Can a set contain different types of objects? T/F (T)

**Comment by SEGrooms** [comment]
Also, point out that you can have a set, {1.2.3.4}, describe a list 1,2,2,2,3,4,4
