### ISSUE TITLE
Discrete Mathematics 5: Set-Builder Notation & Special Sets

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#9]
Hello World! Shawn Grooms again. In this video I wanted to start by introducing set-builder notation and roster notation.
      e.g. A = {1,2,3,4,...}
Before you learn set-builder notation, I must first introduce a few special sets that are also called number systems.
symbol = {... , -1, 0, 1, 2, ...} : "integers"
symbol = {1, 2, 3, ...} : "natural numbers"  i.e. the positive integers
symbol-naught = {0,1,2,3,...} : "whole numbers" i.e. the non-negative integers
Note: This is sometimes still referred to as the natural numbers, but the convention is the natural               numbers are all integers greater than or equal to zero.

So now, whenever you want to refer to the integers, which will be frequent, you can simply write **symbol** instead of natural numbers. What can I say? Mathematicians are lazy. The convenience of this notation allows us to finally use set-builder notation. Keep in mind that the colon ':' in set-builder notation is read as "such that" or "where" or "given" or "given the fact that".

*symbol* = {a/b : a,b *are elements of* *integers*} : "rational numbers"
This is read as, "The rational numbers is the set of all numbers a divided b such that a and b are in the integers." or for a more rigorous definition "The rational numbers is the set of all number that can be expressed as a ratio, or fraction, of integers."

*symbol* = {x : -infinity < x < infinity}: "real numbers"

********************************************************************************************************************
I don't think I'll have to break this video up, but we'll see when I actually go to record it. I think this video will be harder for campers to grasp, as it is quite foreign.

**Comment by jameswinegar** [comment]
"This is read as, "The rational numbers is the set of all numbers a over b such that a and b are integers." or for a more rigorous definition "The rational numbers is the set of all number that can be expressed as a ratio, or fraction, of integers."

Can be rewritten as

"The rational numbers (Q) is the set of all numbers a divided by b such that a and b are in the integers. "

**Comment by jameswinegar** [comment]
remove this

symbol = not a rational number: "irrational numbers"

**Comment by jameswinegar** [comment]
Questions
--------------

Is {1/n : n in Z} a set? T/F (T)
Is {a+bi: a,b in R and i=sqrt(-1)} a set? T/F (T)
What do you think N_{3} would be? MC - {0,1,2} , {1,2}, {1,2,3}, {0,1,2,3}  ( {1,2,3} )

**Comment by SEGrooms** [comment]
Can a set contain no objects? T/F (T)
What's the maximum number of objects a set can have? MC - 2,4,7, infinite (infinite)
Can a set contain different types of objects? T/F (T)
